Repository subply/subply, pull requests merged in 2020-07, with the labels that each got.

#35 [구현완료] [LOGIN] 회원가입 폼
  src/app/header/join/confirmPasswordValidator.ts
  src/app/header/join/join.component.css
  src/app/header/join/join.component.html
  src/app/header/join/join.component.ts
  src/service/user.service.ts
Labels: LOGIN, Review, quest

#39 [구현 완료][TRANSLATE] 동영상 제어
  src/app/main/raw-script/raw-script.component.css
  src/app/main/raw-script/raw-script.component.html
  src/app/main/raw-script/raw-script.component.ts
  src/app/main/translation/translation.component.html
  src/app/main/translation/translation.component.ts
Labels: Review, TRANSLATE, quest

#37 [구현완료] Subply 파일 다운로드
  src/app/header/join/confirmPasswordValidator.ts
  src/app/header/join/join.component.ts
  src/app/main/raw-script/raw-script.component.html
  src/app/main/raw-script/raw-script.component.ts
  src/app/main/translation/translation-reply/translation-reply.component.html
  src/app/main/translation/translation-reply/translation-reply.component.ts
  src/app/model/script.interface.ts
  src/service/scripts.service.ts
Labels: TRANSLATE, quest

#46 [구현 완료] [TRANSLATE] 키보드 제어
  src/app/header/header.component.html
  src/app/main/raw-script/raw-script.component.css
  src/app/main/raw-script/raw-script.component.html
  src/app/main/raw-script/raw-script.component.ts
  src/app/main/url-input/url-input.component.ts
Labels: Review, TRANSLATE

#49 [구현완료] Time format 처리
  src/app/main/raw-script/raw-script.component.html
  src/app/main/raw-script/raw-script.component.ts
  src/app/main/translation/translation-reply/translation-reply.component.ts
  src/app/model/script.interface.ts
Labels: fix
