Repository subply/subply, pull requests merged in 2020-06, with the labels that each got.

#13 [구현 완료] [MAIN] 유튜브 api 호출
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/main/child/child.component.css
  src/app/main/child/child.component.html
  src/app/main/child/child.component.ts
  src/app/main/hook-test/hook-test.component.css
  src/app/main/hook-test/hook-test.component.html
  src/app/main/hook-test/hook-test.component.ts
  src/app/main/raw-script/raw-script.component.css
  src/app/main/raw-script/raw-script.component.html
  src/app/main/raw-script/raw-script.component.spec.ts
  src/app/main/raw-script/raw-script.component.ts
  src/app/main/temp-data/temp-data.model.ts
  src/app/main/translation/translation.component.html
  src/app/main/translation/translation.component.ts
  src/app/main/url-input/url-input.component.ts
  src/service/scripts.service.spec.ts
  src/service/scripts.service.ts
Labels: MAIN, Review

#17 [구현완료] Mypage rest api 호출
  src/app/app.module.ts
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/app/header/header.component.css
  src/app/http-config-inerceptor.service.spec.ts
  src/app/http-config-interceptor.service.ts
  src/app/model/user.interface.ts
  src/app/mypage/mypage.component.css
  src/app/mypage/mypage.component.html
  src/app/mypage/mypage.component.ts
  src/app/mypage/mypage.service.spec.ts
  src/app/mypage/mypage.service.ts
Labels: MYPAGE, Review

#19 [리팩토링 완료] rawScript 컴포넌트
  src/app/main/raw-script/raw-script.component.ts
Labels: TRANSLATE, fix

#22 [구현 완료] 로그인 기능
  .gitignore
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/header/header.component.css
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/header/join/join.component.css
  src/app/header/join/join.component.html
  src/app/header/join/join.component.spec.ts
  src/app/header/join/join.component.ts
  src/app/header/login/login.component.css
  src/app/header/login/login.component.html
  src/app/header/login/login.component.spec.ts
  src/app/header/login/login.component.ts
  src/app/main/mypage/mypage.component.ts
  src/app/main/mypage/mypage.service.ts
  src/service/login.service.spec.ts
  src/service/login.service.ts
  tsconfig.json
Labels: LOGIN, Review, quest

#23 [작업완료] 번역 기능 추가
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.module.ts
  src/app/http-config-interceptor.service.ts
  src/app/main/mypage/mypage.component.html
  src/app/main/mypage/mypage.component.ts
  src/app/main/mypage/mypage.service.ts
  src/app/main/rank/rank.component.ts
  src/app/main/raw-script/raw-script.component.ts
  src/app/main/translation/translation-reply/translation-reply.component.css
  src/app/main/translation/translation-reply/translation-reply.component.html
  src/app/main/translation/translation-reply/translation-reply.component.spec.ts
  src/app/main/translation/translation-reply/translation-reply.component.ts
  src/app/main/translation/translation.component.html
  src/app/main/translation/translation.component.ts
  src/app/main/translation/translation.service.spec.ts
  src/app/main/translation/translation.service.ts
  src/app/model/translation.interface.ts
  src/app/model/user.interface.ts
  src/app/model/userInfo.interface.ts
  src/app/mypage/mypage.component.css
  src/app/mypage/mypage.component.html
  src/app/mypage/mypage.component.ts
Labels: DB, TRANSLATE, fix

#32 [구현 완료] [TRANSLATE] 블럭 초기화
  package-lock.json
  src/app/app.module.ts
  src/app/header/join/confirmPasswordValidator.ts
  src/app/header/join/join.component.html
  src/app/header/join/join.component.ts
  src/app/main/raw-script/raw-script.component.ts
  src/app/main/translation/translation-reply/translation-reply.component.ts
  src/app/main/translation/translation.component.ts
  src/service/scripts.service.ts
Labels: DB, TRANSLATE, quest

#34 [구현완료] Subply vote
  src/app/main/translation/translation-reply/translation-reply.component.html
  src/app/main/translation/translation-reply/translation-reply.component.ts
  src/service/translation.service.ts
Labels: Review, TRANSLATE, quest
